---
title: "Knapsack Experiments"
author: "Michelle King, Maggie Casale"
date: "February 17, 2016"
output: html_document
---

# 5 runs per treatment

First let's load up the data with just 5 runs per treatment.

```{r}
data_15_runs <- read.csv("/home/kingx950/Documents/AI/output15run10000tries.txt", sep="",header=TRUE)

```


```{r, echo=FALSE}
plot(data_15_runs$Score ~ data_15_runs$Search_method,
     xlab="", ylab="Score", horizontal=TRUE, las = 2, par(mar = c(5, 15, 4, 2)+ 0.1))
```

```{r}
pairwise.wilcox.test(data_15_runs$Score, data_15_runs$Search_method)
```

```{r}
data_15_runs$Non_negative_score = ifelse(data_15_runs$Score<0, 0, data_15_runs$Score)

plot(data_15_runs$Non_negative_score ~ data_15_runs$Search_method,
     xlab="", ylab="Score", horizontal=TRUE, las = 2, par(mar = c(5, 15, 4, 2)+ 0.1))
```

```{r}
library("ggplot2")
```


```{r}
twenty_item_problems = subset(data_15_runs, Problem=="kapPI_11_20_1000_4" | Problem=="kapPI_13_20_1000_4" | Problem=="kapPI_16_20_1000_4")

ggplot(twenty_item_problems, aes(Search_method, Non_negative_score)) + geom_boxplot() + facet_grid(. ~ Problem)+ theme_bw(base_size = 8, base_family = "Helvetica")

two_hundren_item_problems = subset(data_15_runs, Problem=="kapPI_11_200_1000_4" | Problem=="kapPI_13_200_1000_4" | Problem=="kapPI_16_200_1000_4")

ggplot(two_hundren_item_problems, aes(Search_method, Non_negative_score)) + geom_boxplot() + facet_grid(. ~ Problem)+ theme_bw(base_size = 8, base_family = "Helvetica")
```

```{r}
ggplot(twenty_item_problems, aes(Search_method, Non_negative_score)) + geom_boxplot() + facet_grid(. ~ Max_evals)

ggplot(two_hundren_item_problems, aes(Search_method, Non_negative_score)) + geom_boxplot() + facet_grid(. ~ Max_evals)
```

```{r}
ggplot(twenty_item_problems, aes(factor(Max_evals), Non_negative_score)) + geom_boxplot() + facet_grid(Problem ~ Search_method)

ggplot(two_hundren_item_problems, aes(factor(Max_evals), Non_negative_score)) + geom_boxplot() + facet_grid(Problem ~ Search_method)
```

```{r}
pairwise.wilcox.test(data_15_runs$Non_negative_score, interaction(data_15_runs$Search_method, data_15_runs$Problem, data_15_runs$Max_evals))
```

```{r}
library("rpart")

rp <- rpart(Non_negative_score ~ Search_method + Problem + Max_evals, data=data_15_runs)
rp
plot(rp, uniform=TRUE)
# summary(rp)
text(rp, use.n = TRUE, cex=0.8, all=TRUE)
printcp(rp)
```
